on:
  push:
    branches: [ "development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy to Server
      if: ${{ success() }}
      run: |
        ssh -o "StrictHostKeyChecking=no" -v -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@13.49.102.181 "cd /var/www/html/interviewing-backend && git pull composer i && php artisan migrate --force"
