name: laravel_deploy

on:
  push:
    branches: [ "development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy to Server
      if: ${{ success() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          cd /var/www/html/interviewing-backend
          git pull
          composer i
          php artisan migrate --force
