name: CI test

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  laravel-tests:

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_PASSWORD: password
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

    - name: Copy .env
      run: |
        cp .env.ci .env
        php artisan key:generate
    - name: Show .env
      run: cat .env
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Restart MySQL Service
      run: sudo service mysql restart
    - name: Check MySQL User Privileges
      run: mysql -u root --password=password -e "SHOW GRANTS FOR 'root'@'localhost';"
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
